# Root DB credentials:
# User: root
# Password: root

# WARNING: Enabling MYSQL_ALLOW_EMPTY_PASSWORD is HIGHLY INSECURE!
# This setting allows the root user to access the database without a password, posing a serious security risk.
# Use only in trusted, isolated, and temporary environments (e.g., local development).
# Instead, prefer setting a strong password with MYSQL_ROOT_PASSWORD (and don't use the example's default one).

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_ALLOW_EMPTY_PASSWORD: true
      # https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html
    #ports:
    #  - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  panel:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql